module SketchupFFI

  attach_function(:SUCameraCreate, [SUCameraRef], SUResult)
  attach_function(:SUCameraRelease, [SUCameraRef], SUResult)
  attach_function(:SUCameraGetOrientation, [SUCameraRef, SUPoint3d, SUPoint3d, SUVector3d], SUResult)
  attach_function(:SUCameraSetOrientation, [SUCameraRef, SUPoint3d, SUPoint3d, SUVector3d], SUResult)
  attach_function(:SUCameraGetViewTransformation, [SUCameraRef, SUTransformation], SUResult)
  attach_function(:SUCameraSetPerspectiveFrustumFOV, [SUCameraRef, :double], SUResult)
  attach_function(:SUCameraGetPerspectiveFrustumFOV, [SUCameraRef, :double_ptr], SUResult)
  attach_function(:SUCameraSetAspectRatio, [SUCameraRef, :double], SUResult)
  attach_function(:SUCameraGetAspectRatio, [SUCameraRef, :double_ptr], SUResult)
  attach_function(:SUCameraSetOrthographicFrustumHeight, [SUCameraRef, :double], SUResult)
  attach_function(:SUCameraGetOrthographicFrustumHeight, [SUCameraRef, :double_ptr], SUResult)
  attach_function(:SUCameraSetPerspective, [SUCameraRef, :bool], SUResult)
  attach_function(:SUCameraGetPerspective, [SUCameraRef, :bool_ptr], SUResult)
  attach_function(:SUCameraGetClippingDistances, [SUCameraRef, :double_ptr, :double_ptr], SUResult)
  attach_function(:SUCameraSetFOVIsHeight, [SUCameraRef, :bool], SUResult)
  attach_function(:SUCameraGetFOVIsHeight, [SUCameraRef, :bool_ptr], SUResult)
  attach_function(:SUCameraSetImageWidth, [SUCameraRef, :double], SUResult)
  attach_function(:SUCameraGetImageWidth, [SUCameraRef, :double_ptr], SUResult)
  attach_function(:SUCameraSetDescription, [SUCameraRef, :string], SUResult)
  attach_function(:SUCameraGetDescription, [SUCameraRef, SUStringRef], SUResult)
  attach_function(:SUCameraGetDirection, [SUCameraRef, SUVector3d], SUResult)
  attach_function(:SUCameraSet2D, [SUCameraRef, :bool], SUResult)
  attach_function(:SUCameraGet2D, [SUCameraRef, :bool_ptr], SUResult)
  attach_function(:SUCameraSetScale2D, [SUCameraRef, :double], SUResult)
  attach_function(:SUCameraGetScale2D, [SUCameraRef, :double_ptr], SUResult)
  attach_function(:SUCameraSetCenter2D, [SUCameraRef, SUPoint3d], SUResult)
  attach_function(:SUCameraGetCenter2D, [SUCameraRef, SUPoint3d], SUResult)

end
