# common.rb
#
module SketchupFFI

  SUResult = enum [
    :SU_ERROR_NONE,
    :SU_ERROR_NULL_POINTER_INPUT,
    :SU_ERROR_INVALID_INPUT,
    :SU_ERROR_NULL_POINTER_OUTPUT,
    :SU_ERROR_INVALID_OUTPUT,
    :SU_ERROR_OVERWRITE_VALID,
    :SU_ERROR_GENERIC,
    :SU_ERROR_SERIALIZATION,
    :SU_ERROR_OUT_OF_RANGE,
    :SU_ERROR_NO_DATA,
    :SU_ERROR_INSUFFICIENT_SIZE,
    :SU_ERROR_UNKNOWN_EXCEPTION,
    :SU_ERROR_MODEL_INVALID,
    :SU_ERROR_MODEL_VERSION,
    :SU_ERROR_LAYER_LOCKED,
    :SU_ERROR_DUPLICATE,
    :SU_ERROR_PARTIAL_SUCCESS,
    :SU_ERROR_UNSUPPORTED,
    :SU_ERROR_INVALID_ARGUMENT,
    :SU_ERROR_ENTITY_LOCKED,
    :SU_ERROR_INVALID_OPERATION
  ]

end
