# face.rb
module SketchupFFI
  attach_function(:SUFaceToEntity, [SUFaceRef], SUEntityRef)
  attach_function(:SUFaceFromEntity, [SUEntityRef], SUFaceRef)
  attach_function(:SUFaceToDrawingElement, [SUFaceRef], SUDrawingElementRef)
  attach_function(:SUFaceFromDrawingElement, [SUDrawingElementRef], SUFaceRef)
  attach_function(:SUFaceCreate, [SUFaceRef, SUPoint3d, SULoopInputRef], SUResult)
  attach_function(:SUFaceCreateSimple, [SUFaceRef, SUPoint3d, :size_t], SUResult)
  attach_function(:SUFaceRelease, [SUFaceRef], SUResult)
  attach_function(:SUFaceGetNormal, [SUFaceRef, SUVector3d], SUResult)
  attach_function(:SUFaceGetNumEdges, [SUFaceRef, :size_ptr], SUResult)
  attach_function(:SUFaceGetEdges, [SUFaceRef, :size_t, SUEdgeRef, :size_ptr], SUResult)
  attach_function(:SUFaceGetNumEdgeUses, [SUFaceRef, :size_ptr], SUResult)
  attach_function(:SUFaceGetEdgeUses, [SUFaceRef, :size_t, SUEdgeUseRef, :size_ptr], SUResult)
  attach_function(:SUFaceGetPlane, [SUFaceRef, SUPlane3d], SUResult)
  attach_function(:SUFaceGetNumVertices, [SUFaceRef, :size_ptr], SUResult)
  attach_function(:SUFaceGetVertices, [SUFaceRef, :size_t, SUVertexRef, :size_ptr], SUResult)
  attach_function(:SUFaceGetOuterLoop, [SUFaceRef, SULoopRef], SUResult)
  attach_function(:SUFaceGetNumInnerLoops, [SUFaceRef, :size_ptr], SUResult)
  attach_function(:SUFaceGetInnerLoops, [SUFaceRef, :size_t, SULoopRef, :size_ptr], SUResult)
  attach_function(:SUFaceAddInnerLoop, [SUFaceRef, SUPoint3d, SULoopInputRef], SUResult)
  attach_function(:SUFaceGetNumOpenings, [SUFaceRef, :size_ptr], SUResult)
  attach_function(:SUFaceGetOpenings, [SUFaceRef, :size_t, SUOpeningRef, :size_ptr], SUResult)
  attach_function(:SUFaceGetFrontMaterial, [SUFaceRef, SUMaterialRef], SUResult)
  attach_function(:SUFaceSetFrontMaterial, [SUFaceRef, SUMaterialRef], SUResult)
  attach_function(:SUFaceGetBackMaterial, [SUFaceRef, SUMaterialRef], SUResult)
  attach_function(:SUFaceSetBackMaterial, [SUFaceRef, SUMaterialRef], SUResult)
  attach_function(:SUFaceIsFrontMaterialAffine, [SUFaceRef, :bool_ptr], SUResult)
  attach_function(:SUFaceIsBackMaterialAffine, [SUFaceRef, :bool_ptr], SUResult)
  attach_function(:SUFaceGetArea, [SUFaceRef, :double_ptr], SUResult)
  attach_function(:SUFaceGetAreaWithTransform, [SUFaceRef, SUTransformation, :double_ptr], SUResult)
  attach_function(:SUFaceIsComplex, [SUFaceRef, :bool_ptr], SUResult)
  attach_function(:SUFaceGetUVHelper, [SUFaceRef, SUTextureWriterRef, SUUVHelperRef], SUResult)
  attach_function(:SUFaceGetUVHelperWithTextureHandle, [SUFaceRef, :bool, :bool, SUTextureWriterRef, :long, SUUVHelperRef], SUResult)
  attach_function(:SUFaceGetNumAttachedDrawingElements, [SUFaceRef, :size_ptr], SUResult)
  attach_function(:SUFaceGetAttachedDrawingElements, [SUFaceRef, :size_t, SUDrawingElementRef, :size_ptr], SUResult)
  attach_function(:SUFaceReverse, [SUFaceRef], SUResult)
end
