require "ffi"

#require_relative "sketchup_ffi/common.rb"
require_relative "sketchup_ffi/base.rb"
require_relative "sketchup_ffi/defs.rb"
require_relative "sketchup_ffi/initialize.rb"

# Structs
require_relative "sketchup_ffi/color.rb"
require_relative "sketchup_ffi/point3d.rb"
require_relative "sketchup_ffi/vector3d.rb"

require_relative "sketchup_ffi/arc_curve.rb"
require_relative "sketchup_ffi/arrow_type.rb"
require_relative "sketchup_ffi/attribute_dictionary.rb"
require_relative "sketchup_ffi/axes.rb"
require_relative "sketchup_ffi/bounding_box.rb"
require_relative "sketchup_ffi/camera.rb"
require_relative "sketchup_ffi/classification_attribute.rb"
require_relative "sketchup_ffi/classification_info.rb"
require_relative "sketchup_ffi/component_definition.rb"
require_relative "sketchup_ffi/component_instance.rb"
require_relative "sketchup_ffi/curve.rb"
require_relative "sketchup_ffi/dimension.rb"
require_relative "sketchup_ffi/dimension_linear.rb"
require_relative "sketchup_ffi/dimension_radial.rb"
require_relative "sketchup_ffi/dimension_style.rb"
require_relative "sketchup_ffi/drawing_element.rb"
require_relative "sketchup_ffi/dynamic_component_attribute.rb"
require_relative "sketchup_ffi/dynamic_component_info.rb"
require_relative "sketchup_ffi/edge.rb"
require_relative "sketchup_ffi/edge_use.rb"
require_relative "sketchup_ffi/entities.rb"
require_relative "sketchup_ffi/entity.rb"
require_relative "sketchup_ffi/entity_list.rb"
require_relative "sketchup_ffi/entity_list_iterator.rb"
require_relative "sketchup_ffi/extension_license.rb"
require_relative "sketchup_ffi/face.rb"
require_relative "sketchup_ffi/font.rb"
require_relative "sketchup_ffi/geometry.rb"
require_relative "sketchup_ffi/geometry_input.rb"
require_relative "sketchup_ffi/group.rb"
require_relative "sketchup_ffi/guide_line.rb"
require_relative "sketchup_ffi/guide_point.rb"
require_relative "sketchup_ffi/image.rb"
require_relative "sketchup_ffi/image_rep.rb"
require_relative "sketchup_ffi/loop_input.rb"
require_relative "sketchup_ffi/material.rb"
require_relative "sketchup_ffi/model.rb"
require_relative "sketchup_ffi/rendering_options.rb"
require_relative "sketchup_ffi/shadow_info.rb"
require_relative "sketchup_ffi/string.rb"
require_relative "sketchup_ffi/typed_value.rb"
require_relative "sketchup_ffi/vertex.rb"

if $0 == __FILE__
  puts  SketchupFFI::ATTACHED_FUNCTIONS
end

